name: Comment on First Line

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  auto_comment:
    uses: prosperity-tech/.github/workflows/pr-blocking-commentor.yml@main
    secrets:
      GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
